name: Build and Deploy
on:
  push:
    branches:
      - main

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy 🚀 (yes, an emoji)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
